### ISSUE TITLE
Feature Request Optimal Compounding & LP

### ISSUE THREAD

**Issue by PowerPress** [Philipp-Sc/terra-rust-bot#1]
Have the bot only stake ANC for optimal compounding factoring gas fee's
Have an option for the bot to stake LP of ANC with optimal compounding factoring gas fee's

**Comment by Philipp-Sc** [comment]
At the moment you can only Auto Stake **ANC Borrowing Rewards**. 

From your comment I get that you want to also be able:

- to Auto Stake **ANC LP Rewards**.
- to Auto Compound the **ANC LP Rewards** back into the ANC LP.

another option is to also implement  Auto LP **ANC Borrowing Rewards**.
(The user might provide a preference like 70%/30% to stake 70% and LP 30% of the ANC.)

I think having these options make sense, I will add these over the next week. Thanks for your input.

**Comment by Philipp-Sc** [comment]
* **ANC Borrowing Rewards** -> **Auto Staked** 
 
Roadmap:

* **ANC Borrowing Rewards** -> **Auto ANC-UST LP**   



* **ANC-UST LP Rewards** -> **Auto Staked**.  
* **ANC-UST LP Rewards** -> **Auto ANC-UST LP**.  



* **Impermanent Loss Damage Control**  (exit the strategy to prevent Impermanent Loss)
* **Auto Farming** (enter LP Farming after ANC stabilized)

**Comment by Philipp-Sc** [comment]
I thought a lot about this.
I am going to use the spectrum protocol to do this. https://terra.spec.finance/vaults

They already have great auto compounding vaults. It is likely not worth implementing the same logic for terra-rust-bot vs just using the spectrum vaults.

An additional feature will be to select any vault to delegate the ANC rewards to.

So basically there will be:

ANC Borrowing Rewards -> Auto Spec Vault

Impermanent Loss Damage Control (exit the spec vault to prevent Impermanent Loss)



~~Auto Farming (enter spec vault after the price stabilized)~~ (Impermanent Loss is mostly a risk if there are big price movements, manually re-entering the vault should be fine. No need for automation here.)

**Comment by Philipp-Sc** [comment]
regarding **Anchor Auto Farm Rewards**

ANC Borrowing Rewards -> Auto Spec Vault

 is now available.

`-b anchor_auto_lp`

**Comment by PowerPress** [comment]
How are you determining optimum time to compound? This is a slick method: https://compoundornot.com/ but issue is you are getting a distribution yield of ANC around 10% and then getting LP 100%+. Where that webapp does not let you take this into consideration. In additional you have 2 gas fee's as well.

**Comment by Philipp-Sc** [comment]
Here is how the auto farming works. (The auto compounding is done by spectrum protocol)

(I use the same code to calculate the optimum time for auto staking. )
Currently the pool APY of about 80% is used to determine the time for the next transaction.

I do not use the APY that includes the auto compounding (~120%+) because the returns are not linear. 
This is because how the function I wrote works:

I partition the year into hourly time frames. 
Then I calculate the ANC rewards per time frame using the distribution APR.
Also the Staking/Farming rewards per time frame. 

I use this to calculate the returns that would occur if the rewards were claimed and provided. (includes the fees)
This is done for each point in time. (0..365*24)
This way it finds the optimum between waiting vs the benefit of staking/farming early.

E.g.
- the last time frame would include all the ANC rewards but zero staking/farming returns.
- the first time frame would include zero ANC rewards and the full staking/farming percentage but resulting in zero returns.

For the Spectrum ANC-UST LP Vault this calculation will result in a later auto farming date than optimal.

I am not sure this is a problem since if I were to extend the function to use the auto compound apy of ~120% this would likely lead to a premature auto farming date, because the APY is likely to go down over course of the year. 

What do you think?

**Comment by PowerPress** [comment]
Great ideas, I think you should use the auto compounding apy even though they will change we don’t know for how long so use best information available at the moment and gave it say weekly or daily recalculate new best auto compounding rate. Would love to have a rest option so I could determine say best autocompounding with other non supported farms.

**Comment by Philipp-Sc** [comment]
The next date, when to deposit into the vault is recalculated every minute or so.
I need to find a function to break the APY down per hours.

E.g 
364x24 -> APR equals 70%
...
...
0 ->  APR equals 120%+

the difficult part is in between since the auto compound APY is non linear.

Spectrum protocol provides the rate if compounded daily, which we could use.

so for each day passed we divide the APR with `120% / Math.pow(1+(compounded_daily_rate),number_of_days)`
the only problem I have with this is that I do not end up at the exact APR of 70%. Something close but not 70%..

Maybe it is because some percentages of the APY go to Spectrum protocol?

**Comment by PowerPress** [comment]
It’s possible it’s the spec token. Check the calculations in this GitHub to see if it helps: https://github.com/kowit/compound-or-not
Here is another resource: https://docs.google.com/spreadsheets/d/1-Nougd_Ra6sz_cwAizsIb65gd9gL94LpjjKyKP4uAm4/edit?usp=sharing

I hope this helps

**Comment by Philipp-Sc** [comment]
Thank you, I will add an option for users to decide which APY to use:

a) pool APY 
b) compound APY

**Comment by PowerPress** [comment]
Could you add option to manually enter APR/APY and gas fee numbers so this could be used for other non supported coins to determine when to compound, how often and minimum amount of coins and etc.

**Comment by Philipp-Sc** [comment]
I added a way for you to access the function, be aware the method assumes the apys scale linearly. 
```
 ./test/build/bin/ctlscript.sh utils
Select method:
1) estimate_optimal_next_claim_and_stake_tx
1
Loan amount: (the balance you earn distribution rewards on)
15000
Distribution apr: 
0.06
Pending rewards: (already accumulated pending rewards)
0
Pool apy: (the apy of the pool you provide the distribution rewards to)
0.09
Transaction fee: (the fee to claim and provide the rewards per transaction)
0.11

```
```
Expected returns without any automation: "899.9927397260273972602730725"
Expected returns with automation: "947.8377" (+"5.3162"%)
Date next: "27/04/22 06:56" 
Duration next: "4d, 1h, 0m" 
Value next: "9.9658" 

```

**Comment by Philipp-Sc** [comment]
I have not yet added:

 b) compound APY

at the moment this is not a priority for me. The reason is that the last day/compounding for an auto compound APY has the biggest influence on the final returns. But there is no way to know if the given APY is still the same 365 days later. The margin of error seems to be rather high for an estimate to be useful.

**Comment by Philipp-Sc** [comment]
created a new issue for IL #3 

feel free to re-open this case if needed.
